baseurl = "/"
name = "Byron Mansfield"
title = "Byron Mansfield"
languageCode = "en-us"
theme = "casper"
pluralizelisttitles = "false"

[[menu.main]]
  name = "My Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "About"
  weight = -110
  identifier = "about"
  url = "/about"
